spring:
  application:
    name: bank-aplication

  flyway:
    enabled: true
    lock-retry-count: 10
    locations: classpath:db/migration
    create-schemas: true
    schemas: bank
    default-schema: bank
    loggers: slf4j
    baseline-on-migrate: true
    baseline-version: 1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: false

  web:
    resources:
      add-mappings: false

token:
  access-token-expire-time: 15 # minutes
  refresh-token-expire-time: 30 # minutes
  verification-token-expire-time: 1 # days



