spring:
  application:
    name: bank-aplication

  flyway:
    lock-retry-count: 10
    create-schemas: true
    schemas: bank
    default-schema: bank
    enabled: true
    loggers: slf4j

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

token:
  access-token-expire-time: 15 # minutes
  refresh-token-expire-time: 30 # minutes
  verification-token-expire-time: 1 # days



