CREATE SEQUENCE bank.accounts_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE bank.address_infos_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE bank.customers_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE bank.employees_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE bank.identity_users_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE bank.postings_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE bank.transfers_seq START WITH 1 INCREMENT BY 50;
