CREATE TABLE bank.accounts
(
    deleted_at  TIMESTAMP,
    id          NUMBER(38, 0) NOT NULL,
    card_number VARCHAR2(255) NOT NULL,
    currency    VARCHAR2(255) NOT NULL,
    balance     DECIMAL   NOT NULL,
    customer_id NUMBER(38, 0) NOT NULL,
    status      VARCHAR2(255) NOT NULL,
    created_at  TIMESTAMP,
    due_to      TIMESTAMP NOT NULL,
    updated_at  TIMESTAMP,
    CONSTRAINT pk_accounts PRIMARY KEY (id)
);

CREATE TABLE bank.activation_tokens
(
    id                    NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id               NUMBER(38, 0)                                  NOT NULL,
    activation_token_hash VARCHAR2(255)                                  NOT NULL,
    expires_at            TIMESTAMP NOT NULL,
    CONSTRAINT pk_activation_tokens PRIMARY KEY (id)
);

CREATE TABLE bank.address_infos
(
    id          NUMBER(38, 0) NOT NULL,
    country     VARCHAR2(255) NOT NULL,
    region      VARCHAR2(255) NOT NULL,
    city        VARCHAR2(255) NOT NULL,
    address     VARCHAR2(255) NOT NULL,
    postal_code VARCHAR2(255) NOT NULL,
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP,
    version     NUMBER(38, 0),
    CONSTRAINT pk_address_infos PRIMARY KEY (id)
);

CREATE TABLE bank.customers
(
    deleted_at       TIMESTAMP,
    id               NUMBER(38, 0) NOT NULL,
    identity_user_id NUMBER(38, 0) NOT NULL,
    first_name       VARCHAR2(255) NOT NULL,
    last_name        VARCHAR2(255) NOT NULL,
    middle_name      VARCHAR2(255) NOT NULL,
    gender           VARCHAR2(255) NOT NULL,
    address_info_id  NUMBER(38, 0),
    created_at       TIMESTAMP,
    updated_at       TIMESTAMP,
    version          NUMBER(38, 0),
    CONSTRAINT pk_customers PRIMARY KEY (id)
);

CREATE TABLE bank.employees
(
    id               NUMBER(38, 0) NOT NULL,
    identity_user_id NUMBER(38, 0) NOT NULL,
    first_name       VARCHAR2(255) NOT NULL,
    last_name        VARCHAR2(255) NOT NULL,
    middle_name      VARCHAR2(255) NOT NULL,
    gender           VARCHAR2(255) NOT NULL,
    CONSTRAINT pk_employees PRIMARY KEY (id)
);

CREATE TABLE bank.identity_users
(
    deleted_at               TIMESTAMP,
    id                       NUMBER(38, 0) NOT NULL,
    email                    VARCHAR2(255) NOT NULL,
    password_hash            VARCHAR2(255) NOT NULL,
    phone_number             VARCHAR2(255) NOT NULL,
    alternative_phone_number VARCHAR2(255),
    role                     VARCHAR2(255) NOT NULL,
    status                   NUMBER(5)     NOT NULL,
    created_at               TIMESTAMP,
    updated_at               TIMESTAMP,
    version                  NUMBER(38, 0),
    CONSTRAINT pk_identity_users PRIMARY KEY (id)
);

CREATE TABLE bank.postings
(
    deleted_at  TIMESTAMP,
    id          NUMBER(38, 0) NOT NULL,
    account_id  NUMBER(38, 0) NOT NULL,
    type        VARCHAR2(255),
    amount      DECIMAL,
    description VARCHAR2(255),
    transfer_id NUMBER(38, 0) NOT NULL,
    created_at  TIMESTAMP NOT NULL,
    CONSTRAINT pk_postings PRIMARY KEY (id)
);

CREATE TABLE bank.refresh_tokens
(
    id                 NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id            NUMBER(38, 0)                                  NOT NULL,
    refresh_token_hash VARCHAR2(255)                                  NOT NULL,
    expires_at         TIMESTAMP NOT NULL,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id)
);

CREATE TABLE bank.transfers
(
    deleted_at          TIMESTAMP,
    id                  NUMBER(38, 0) NOT NULL,
    from_number         VARCHAR2(255) NOT NULL,
    to_number           VARCHAR2(255) NOT NULL,
    currency            VARCHAR2(255) NOT NULL,
    amount              DECIMAL NOT NULL,
    transaction_status  VARCHAR2(255) NOT NULL,
    transaction_comment VARCHAR2(255),
    created_at          TIMESTAMP,
    CONSTRAINT pk_transfers PRIMARY KEY (id)
);

ALTER TABLE bank.refresh_tokens
    ADD CONSTRAINT uc_0efae3d0c8b6dbeef39e7f3a4 UNIQUE (user_id, refresh_token_hash);

ALTER TABLE bank.accounts
    ADD CONSTRAINT uc_accounts_card_number UNIQUE (card_number);

ALTER TABLE bank.activation_tokens
    ADD CONSTRAINT uc_activation_tokens_user UNIQUE (user_id);

ALTER TABLE bank.activation_tokens
    ADD CONSTRAINT uc_c0b7f8ff30e4640902beeae7a UNIQUE (user_id, activation_token_hash);

ALTER TABLE bank.customers
    ADD CONSTRAINT uc_customers_address_info UNIQUE (address_info_id);

ALTER TABLE bank.customers
    ADD CONSTRAINT uc_customers_identity_user UNIQUE (identity_user_id);

ALTER TABLE bank.employees
    ADD CONSTRAINT uc_employees_identity_user UNIQUE (identity_user_id);

ALTER TABLE bank.identity_users
    ADD CONSTRAINT uc_identity_users_email UNIQUE (email);

ALTER TABLE bank.identity_users
    ADD CONSTRAINT uc_identity_users_phone_number UNIQUE (phone_number);

ALTER TABLE bank.refresh_tokens
    ADD CONSTRAINT uc_refresh_tokens_user UNIQUE (user_id);

ALTER TABLE bank.accounts
    ADD CONSTRAINT FK_ACCOUNTS_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES bank.customers (id);

ALTER TABLE bank.activation_tokens
    ADD CONSTRAINT FK_ACTIVATION_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES bank.identity_users (id);

ALTER TABLE bank.customers
    ADD CONSTRAINT FK_CUSTOMERS_ON_ADDRESS_INFO FOREIGN KEY (address_info_id) REFERENCES bank.address_infos (id);

ALTER TABLE bank.customers
    ADD CONSTRAINT FK_CUSTOMERS_ON_IDENTITY_USER FOREIGN KEY (identity_user_id) REFERENCES bank.identity_users (id);

ALTER TABLE bank.employees
    ADD CONSTRAINT FK_EMPLOYEES_ON_IDENTITY_USER FOREIGN KEY (identity_user_id) REFERENCES bank.identity_users (id);

ALTER TABLE bank.postings
    ADD CONSTRAINT FK_POSTINGS_ON_ACCOUNT FOREIGN KEY (account_id) REFERENCES bank.accounts (id);

ALTER TABLE bank.postings
    ADD CONSTRAINT FK_POSTINGS_ON_TRANSFER FOREIGN KEY (transfer_id) REFERENCES bank.transfers (id);

ALTER TABLE bank.refresh_tokens
    ADD CONSTRAINT FK_REFRESH_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES bank.identity_users (id);