ALTER SESSION SET CONTAINER = FREEPDB1;

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLESPACE BANK_SPACE DATAFILE ''BANK_SPACE.dbf'' SIZE 100M AUTOEXTEND ON';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1543 THEN RAISE; END IF; -- Пропускаємо, якщо вже існує
END;
/

DECLARE
v_count NUMBER;
BEGIN
SELECT count(*) INTO v_count FROM dba_users WHERE username = 'BANK';
IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER bank IDENTIFIED BY bank1234 DEFAULT TABLESPACE BANK_SPACE';
END IF;
END;
/

GRANT DBA TO bank;
GRANT CONNECT, RESOURCE TO bank;
ALTER USER bank QUOTA UNLIMITED ON BANK_SPACE;

SELECT username, common FROM dba_users WHERE username = 'BANK';